package system;

import java.io.Serializable;
import java.util.List;

import api.Result;
import api.Task;

/**
 * Implementation of the {@link api.Result Result} interface
 * 
 * @author Manasa Chandrasekhar
 * @author Kowshik Prakasam
 */
public class ResultImpl<T> implements Result<T>, Serializable {

	private static final long serialVersionUID = -7688137730920618986L;
	private T result;
	private List<Task<T>> subTasks;
	private String taskId;
	private String taskParentId;

	/**
	 * Default constructor
	 */
	
	public ResultImpl(String taskId, String taskParentId) {
		this.result = null;
		this.subTasks = null;
		this.taskId=taskId;
		this.taskParentId=taskParentId;
	}

	/**
	 * @return Returns the value computed by the task
	 * 
	 * 
	 */
	@Override
	public T getValue() {
		return this.result;
	}

	/**
	 * @return Returns sub tasks generated by the underlying computation using
	 *         divide and conquer
	 */
	@Override
	public List<Task<T>> getSubTasks() {
		return this.subTasks;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see api.Result#setValue(java.lang.Object)
	 */
	@Override
	public void setValue(T value) {
		this.result = value;

	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see api.Result#setSubTasks(java.util.List)
	 */
	@Override
	public void setSubTasks(List<Task<T>> subTasks) {
		this.subTasks = subTasks;
	}

	/* (non-Javadoc)
	 * @see api.Result#getId()
	 */
	@Override
	public String getId() {
		return taskId;
	}

	/* (non-Javadoc)
	 * @see api.Result#getParentId()
	 */
	@Override
	public String getParentId() {
		return taskParentId;
	}

}
